SHELL = /usr/bin/env bash
include Makefile.config
export ARCH

boot_ocamlc = main_native.exe
boot_ocamlopt = optmain_native.exe
boot_ocamlmklib = tools/ocamlmklib.exe
boot_ocamldep = tools/ocamldep.exe
boot_ocamlobjinfo = tools/objinfo.exe
ocamldir = .
#toplevels_installed = top opttop
toplevels_installed = top

include Makefile.common-jst
